//------------------------------------------------------------------------------
//                  Arena's & Daggerfall's Text Tags Codes
//------------------------------------------------------------------------------
#define dfReturn        0x00
#define dfEOP           0xF6    //end of page
#define df0xF8          0xF8    //0xF8
#define dfFont          0xF9    //selecting font number
#define df0xFA          0xFA    //0xFA
#define dfOffset        0xFB    //offset in pixels
#define dfCRRight       0xFC    //carriage return right adjusted
#define dfCRCenter      0xFD    //carriage return centered
#define dfEOB           0xFE    //end of block
#define dfEOR           0xFF    //end of random list
//Arena
#define dfDEL           0x08
#define dfTAB           0x09
#define dfCR            0x0D
#define df0x0A          0x0A
#define df0x60          0x60
#define df0xC0          0xC0
#define df0xD4          0xD4
#define df0xD6          0xD6
#define df0xD8          0xD8
#define dfLF            0x00
//----------------------------------------------------------------------
#define dftEOP          "<0xF6>"//end of page
#define dft0xF8         "<0xF8>"//0xF8
#define dftFont         "<0xF9="//selecting font number
#define dft0xFA         "<0xFA="//0xFA
#define dftOffset       "<0xFB="//offset in pixels
#define dftCRRight      "<0xFC>"//carriage return right adjusted
#define dftCRCenter     "<0xFD>"//carriage return centered
#define dftEOB          "<0xFE>"//end of block
#define dftEOR          "<0xFF>"//end of random list
//Arena
#define dftDEL          "<0x08>"
#define dftTAB          "<0x09>"
#define dftCR           "<0x0D>"
#define dft0x0A         "<0x0A>"
#define dft0x60         "<0x60>"
#define dft0xC0         "<0xC0>"
#define dft0xD4         "<0xD4>"
#define dft0xD6         "<0xD6>"
#define dft0xD8         "<0xD8>"
#define dftLF           "*"

#define dfVar1          '%'     //variables signature
#define dfVar2          '#'     //variables signature (Arena)
#define dfVar3          '&'     //variables signature (Arena)

